version: '3;8'

services:

  engine:
    restart: on-failure

    build:
      context: . 
      dockerfile: Dockerfile
    
    volumes:
      - .:/app
    ports:
      - '8000:8000'

    command: uvicorn backend.main:app --reload --host 0.0.0.0
